pub mod c;
pub mod calls;
pub mod cognitive_complexity;
pub mod comments;
pub mod duplicate_fns;
pub mod duplicate_logic;
pub mod file_sizes;
pub mod mod_count;
pub mod modules;
pub mod private_fn_naming;
mod s;
pub mod t;
pub mod tree_structure;
