pub mod c;
pub mod call_rules;
pub mod cognitive_complexity;
pub mod comment_rules;
pub mod duplicate_fns;
pub mod duplicate_logic;
pub mod file_sizes;
pub mod mod_count;
pub mod mod_lib_contents;
pub mod mod_location;
pub mod mod_over_file;
pub mod private_fn_naming;
mod s;
pub mod t;
pub mod tree_structure;
pub mod use_privacy;
