[mod-count]
ignore = ["src/checks"]

[duplicate-fns]
ignore = [
    "src/checks/call_rules/main.rs::run",
    "src/checks/cognitive_complexity/main.rs::run",
    "src/checks/tree_structure/common_reexport/c_contents/main.rs::check"
]

[duplicate-logic]
ignore = ["ef274c63"]