[mod-count]
ignore = ["src/rules"]

[duplicate-fns]
ignore = [
    "src/rules/call_rules/main.rs::run",
    "src/rules/cognitive_complexity/main.rs::run",
    "src/rules/tree_structure/common_reexport/c_contents/main.rs::run"
]

[duplicate-logic]
ignore = ["b841dd53"]